image: trion/ng-cli-karma

stages:
  - install
  - lint
  - build
  - deploy

cache:
  paths:
    - node_modules/

install_stage:
  stage: install
  script:
    - rm ./package-lock.json
    - npm install

lint_stage:
  stage: lint
  script:
    - ./node_modules/@angular/cli/bin/ng lint
    
build_stage:
  stage: build
  script:
    - ./node_modules/@angular/cli/bin/ng build

deploy_prod:
  stage: deploy
  when: manual
  only:
    - master
  environment:
    name: production
    url: https://pddbel.tk
  script:
    - echo "deploy prod"

deploy_dev:
  stage: deploy
  only:
    - dev
  environment:
    name: development
    url: https://dev.pddbel.tk
  script:
    - rsync -av --delete public /srv/nginx/$CI_COMMIT_REF_SLUG
