image: trion/ng-cli-karma

cache:
  paths:
    - node_modules/

build_stage:
  stage: build
  environment: Stage
    - rm ./package-lock.json
    - npm install
    - ./node_modules/@angular/cli/bin/ng lint
    - ./node_modules/@angular/cli/bin/ng build