image: node:latest

stages:
  - install
  - lint
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm install

lint_stage:
  stage: lint
  script:
    - ./node_modules/@angular/cli/bin/ng lint
    
build_stage:
  stage: build
  script:
    - ./node_modules/@angular/cli/bin/ng build --progress false

deploy_prod:
  stage: deploy
  when: manual
  before_script:
    - apt-get update -qq && apt-get install -y -qq sshpass
  only:
    - master
  environment:
    name: production
    url: https://pddbel.tk
  script:
    - echo "deploy prod"

deploy_dev:
  before_script:
    - apt-get update -qq && apt-get install -y -qq sshpass
  stage: deploy
  only:
    - dev
  environment:
    name: development
    url: https://dev.pddbel.tk
  script:
    - echo "deploy dev"