image: trion/ng-cli-karma

trigger_build:
  stage: deploy
  script:
    - "curl -X POST -F token=f0b98eaa735a6e5afad728b9211ea2 -F ref=dev https://gitlab.com/api/v4/projects/7705408/trigger/pipeline"

cache:
  paths:
    - node_modules/

deploy_stage:
  stage: deploy
  environment: Stage
  script:
    - rm ./package-lock.json
    - npm install
    - ./node_modules/@angular/cli/bin/ng lint