image: trion/ng-cli-karma

cache:
  paths:
    - node_modules/

deploy_stage:
  stage: deploy
  environment: Stage
  script:
    - rm ./package-lock.json
    - npm install
    - npm lint
    - ./node_modules/@angular/cli/bin/ng test --progress false --single-run=true --watch=false