image: node:latest

stages:
  - install
  - lint
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm install

lint_stage:
  stage: lint
  script:
    - ./node_modules/@angular/cli/bin/ng lint
    
build_stage:
  stage: build
  artifacts:
    paths: 
      - dist
  script:
    - ./node_modules/@angular/cli/bin/ng build --progress false

deploy_prod:
  stage: deploy
  when: manual
  before_script:
    - apt-get update -qq && apt-get install -y -qq sshpass
  only:
    - master
    - merge-requests
  environment:
    name: production
    url: https://pddbel.tk
  script:
    - sshpass -V
    - export SSHPASS=$SSH_PASS 
    - sshpass -e scp -o stricthostkeychecking=no -r ./dist/. root@pddbel.tk:/var/www/html/prod

deploy_dev:
  stage: deploy
  before_script:
    - apt-get update -qq && apt-get install -y -qq sshpass
  only:
    - dev
    - merge-requests
  environment:
    name: production
    url: https://dev.pddbel.tk
  script:
    - sshpass -V
    - export SSHPASS=$SSH_PASS 
    - sshpass -e scp -o stricthostkeychecking=no -r ./dist/. root@pddbel.tk:/var/www/html/dev