image: trion/ng-cli-karma

cache:
  paths:
    - node_modules/

build_stage:
  start: build
  environment: Stage
  script:
    - rm ./package-lock.json
    - npm install

test_stage:
  start: test
  environment: Stage
  script:
    - ./node_modules/@angular/cli/bin/ng lint
    

deploy_stage:
  stage: deploy
  environment: Stage
  script:
    - ./node_modules/@angular/cli/bin/ng build